Atomics load add
Samsung/node-jerryscript pull request #68
Opened 2020-10-12 08:29 UTC by rwalczyna

Parallel tests:
Before: +1475 | -1005
After : +1516 | -964

#63 Should be merged first.

2020-10-12 09:48 UTC, rerobika commented
Please rebase.

2020-10-12 09:50 UTC, rerobika requested changes
Only one request. Can you separate these operations into an individual source file?

2020-10-12 11:11 UTC, rerobika commented
Also please keep in mind during rebasing that 3d43aa82e826ba6cfb787f412f88de55a6b30182 moved the `deps/jerry/jerryscript` directory into a submodule.

2020-10-12 13:21 UTC, rwalczyna commented
I rebased the commit and moved Atomics methods to jerry_atomics.
I also moved functions used to register handlers (jerryx_handler_register_*) to utils - to use them outside of jerry_isolate.

'parallel' suite before (3d43aa82e826ba6cfb787f412f88de55a6b30182):
[14:30|% 100|+ 1588|- 892]: Done
after:
[12:38|% 100|+ 1640|- 840]: Done

2020-10-12 13:23 UTC, rerobika reviewed
LGTM, after these minor changes.

2020-10-12 13:23 UTC, rerobika commented on deps/jerry/v8jerry/v8jerry_atomics.cpp
> +}  // namespace JerryAtomics
Please add new line at the end of the file.

2020-10-12 13:23 UTC, rerobika commented on deps/jerry/v8jerry/v8jerry_utils.cpp
> +}
Ditto.

2020-10-15 07:19 UTC, rerobika approved these changes
LGTM

2020-10-15 07:20 UTC, merged